receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  debug:
    verbosity: detailed
  otlp/dashboard:
    endpoint: ${env:DASHBOARD_URL}
    tls:
      insecure: true

processors:
  batch:

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/dashboard, debug]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/dashboard, debug]