#https://grafana.com/docs/grafana/latest/administration/provisioning/
apiVersion: 1

datasources:
- name: Tempo
  type: tempo
  uid: tempo
  access: proxy
  url: ${TEMPO_URL}
  basicAuth: false
  isDefault: false
  version: 1
  editable: false

- name: Loki
  type: loki
  uid: loki
  access: proxy
  url: ${LOKI_URL}
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
  jsonData:
    derivedFields:
        - name: 'trace_id'
          matcherType: 'label'
          matcherRegex: 'trace_id'
          url: '$${__value.raw}'
          datasourceUid: 'tempo'
          urlDisplayLabel: 'Tempo'